// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AuthRefundWithdrawRequestBodyRefundAmount struct {
	Currency *string `json:"currency,omitempty"`
	Value    *string `json:"value,omitempty"`
}

func (o *AuthRefundWithdrawRequestBodyRefundAmount) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *AuthRefundWithdrawRequestBodyRefundAmount) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

type AuthRefundWithdrawRequestBody struct {
	AccountToken               *string                                    `json:"accountToken,omitempty"`
	MerchantID                 *string                                    `json:"merchantId,omitempty"`
	OriginalCaptureNo          *string                                    `json:"originalCaptureNo,omitempty"`
	OriginalPartnerReferenceNo *string                                    `json:"originalPartnerReferenceNo,omitempty"`
	PartnerRefundNo            *string                                    `json:"partnerRefundNo,omitempty"`
	PublicUserID               *string                                    `json:"publicUserId,omitempty"`
	Reason                     *string                                    `json:"reason,omitempty"`
	RefundAmount               *AuthRefundWithdrawRequestBodyRefundAmount `json:"refundAmount,omitempty"`
}

func (o *AuthRefundWithdrawRequestBody) GetAccountToken() *string {
	if o == nil {
		return nil
	}
	return o.AccountToken
}

func (o *AuthRefundWithdrawRequestBody) GetMerchantID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantID
}

func (o *AuthRefundWithdrawRequestBody) GetOriginalCaptureNo() *string {
	if o == nil {
		return nil
	}
	return o.OriginalCaptureNo
}

func (o *AuthRefundWithdrawRequestBody) GetOriginalPartnerReferenceNo() *string {
	if o == nil {
		return nil
	}
	return o.OriginalPartnerReferenceNo
}

func (o *AuthRefundWithdrawRequestBody) GetPartnerRefundNo() *string {
	if o == nil {
		return nil
	}
	return o.PartnerRefundNo
}

func (o *AuthRefundWithdrawRequestBody) GetPublicUserID() *string {
	if o == nil {
		return nil
	}
	return o.PublicUserID
}

func (o *AuthRefundWithdrawRequestBody) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

func (o *AuthRefundWithdrawRequestBody) GetRefundAmount() *AuthRefundWithdrawRequestBodyRefundAmount {
	if o == nil {
		return nil
	}
	return o.RefundAmount
}

type AuthRefundWithdrawRequest struct {
	AuthorizationCustomer *string                        `header:"style=simple,explode=false,name=Authorization-Customer"`
	ChannelID             *string                        `header:"style=simple,explode=false,name=Channel-ID"`
	RequestBody           *AuthRefundWithdrawRequestBody `request:"mediaType=application/json"`
	XClientKey            *string                        `header:"style=simple,explode=false,name=X-Client-Key"`
	XExternalID           *string                        `header:"style=simple,explode=false,name=X-EXTERNAL-ID"`
	XSignature            *string                        `header:"style=simple,explode=false,name=X-Signature"`
	XTimestamp            *string                        `header:"style=simple,explode=false,name=X-Timestamp"`
}

func (o *AuthRefundWithdrawRequest) GetAuthorizationCustomer() *string {
	if o == nil {
		return nil
	}
	return o.AuthorizationCustomer
}

func (o *AuthRefundWithdrawRequest) GetChannelID() *string {
	if o == nil {
		return nil
	}
	return o.ChannelID
}

func (o *AuthRefundWithdrawRequest) GetRequestBody() *AuthRefundWithdrawRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *AuthRefundWithdrawRequest) GetXClientKey() *string {
	if o == nil {
		return nil
	}
	return o.XClientKey
}

func (o *AuthRefundWithdrawRequest) GetXExternalID() *string {
	if o == nil {
		return nil
	}
	return o.XExternalID
}

func (o *AuthRefundWithdrawRequest) GetXSignature() *string {
	if o == nil {
		return nil
	}
	return o.XSignature
}

func (o *AuthRefundWithdrawRequest) GetXTimestamp() *string {
	if o == nil {
		return nil
	}
	return o.XTimestamp
}

type AuthRefundWithdrawResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AuthRefundWithdrawResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AuthRefundWithdrawResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AuthRefundWithdrawResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
