// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AdditionalInfo struct {
	MerchantID *string `json:"merchantId,omitempty"`
}

func (o *AdditionalInfo) GetMerchantID() *string {
	if o == nil {
		return nil
	}
	return o.MerchantID
}

type GenerateB2b2cTokenRequestBody struct {
	AdditionalInfo *AdditionalInfo `json:"additionalInfo,omitempty"`
	AuthCode       *string         `json:"authCode,omitempty"`
	GrantType      *string         `json:"grantType,omitempty"`
}

func (o *GenerateB2b2cTokenRequestBody) GetAdditionalInfo() *AdditionalInfo {
	if o == nil {
		return nil
	}
	return o.AdditionalInfo
}

func (o *GenerateB2b2cTokenRequestBody) GetAuthCode() *string {
	if o == nil {
		return nil
	}
	return o.AuthCode
}

func (o *GenerateB2b2cTokenRequestBody) GetGrantType() *string {
	if o == nil {
		return nil
	}
	return o.GrantType
}

type GenerateB2b2cTokenRequest struct {
	RequestBody *GenerateB2b2cTokenRequestBody `request:"mediaType=application/json"`
	XClientKey  *string                        `header:"style=simple,explode=false,name=X-Client-Key"`
	XSignature  *string                        `header:"style=simple,explode=false,name=X-Signature"`
	XTimestamp  *string                        `header:"style=simple,explode=false,name=X-Timestamp"`
}

func (o *GenerateB2b2cTokenRequest) GetRequestBody() *GenerateB2b2cTokenRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *GenerateB2b2cTokenRequest) GetXClientKey() *string {
	if o == nil {
		return nil
	}
	return o.XClientKey
}

func (o *GenerateB2b2cTokenRequest) GetXSignature() *string {
	if o == nil {
		return nil
	}
	return o.XSignature
}

func (o *GenerateB2b2cTokenRequest) GetXTimestamp() *string {
	if o == nil {
		return nil
	}
	return o.XTimestamp
}

// GenerateB2b2cTokenResponseBody - Generate B2B2C token response
type GenerateB2b2cTokenResponseBody struct {
	AccessToken     *string `json:"accessToken,omitempty"`
	ExpiresIn       *string `json:"expiresIn,omitempty"`
	ResponseCode    *string `json:"responseCode,omitempty"`
	ResponseMessage *string `json:"responseMessage,omitempty"`
	ResponseTime    *string `json:"responseTime,omitempty"`
	TokenType       *string `json:"tokenType,omitempty"`
}

func (o *GenerateB2b2cTokenResponseBody) GetAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.AccessToken
}

func (o *GenerateB2b2cTokenResponseBody) GetExpiresIn() *string {
	if o == nil {
		return nil
	}
	return o.ExpiresIn
}

func (o *GenerateB2b2cTokenResponseBody) GetResponseCode() *string {
	if o == nil {
		return nil
	}
	return o.ResponseCode
}

func (o *GenerateB2b2cTokenResponseBody) GetResponseMessage() *string {
	if o == nil {
		return nil
	}
	return o.ResponseMessage
}

func (o *GenerateB2b2cTokenResponseBody) GetResponseTime() *string {
	if o == nil {
		return nil
	}
	return o.ResponseTime
}

func (o *GenerateB2b2cTokenResponseBody) GetTokenType() *string {
	if o == nil {
		return nil
	}
	return o.TokenType
}

type GenerateB2b2cTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Generate B2B2C token response
	Object *GenerateB2b2cTokenResponseBody
}

func (o *GenerateB2b2cTokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateB2b2cTokenResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *GenerateB2b2cTokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateB2b2cTokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenerateB2b2cTokenResponse) GetObject() *GenerateB2b2cTokenResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
